/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Janela para adicionar, remover, editar e ordenar alunos de um curso.
 * É chamada pelas telas CursoCadastrar e CursoEditar.
 * 
 * - Duplo clique em um nome: edita o aluno.
 * - Botões permitem adicionar, remover e ordenar nomes.
 * - Ao fechar, devolve a lista atualizada para a tela que chamou.
 * 
 * @author luiza
 */
public class AdicionarAlunos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(AdicionarAlunos.class.getName());

    private DefaultListModel<String> modeloLista;
    private List<String> alunos;
    private JFrame parent; // Tela que chamou (CursoCadastrar ou CursoEditar)

    // 🔹 Construtor que recebe o parent e a lista
    public AdicionarAlunos(JFrame parent, List<String> alunos) {
        initComponents();
        this.parent = parent;
        this.alunos = alunos != null ? new ArrayList<>(alunos) : new ArrayList<>();
        configurarLista();
        preencherLista();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            if (parent != null) {
                if (parent instanceof CursoCadastrar cadastrar) {
                    cadastrar.atualizarListaAlunos(getAlunosAtualizados());
                    cadastrar.setVisible(true);
                } else if (parent instanceof CursoEditar editar) {
                    editar.atualizarListaAlunos(getAlunosAtualizados());
                    editar.setVisible(true);
                }
            }
        }
    });
    }

    // 🔹 Construtor padrão (caso seja aberto isoladamente para teste)
    public AdicionarAlunos() {
        initComponents();
        this.alunos = new ArrayList<>();
        configurarLista();
    }

    // 🔹 Configura o modelo da lista
    private void configurarLista() {
        modeloLista = new DefaultListModel<>();
        listNomeAlunos.setModel(modeloLista);
    }

    // 🔹 Preenche a lista inicial
    private void preencherLista() {
        modeloLista.clear();
        for (String aluno : alunos) {
            modeloLista.addElement(aluno);
        }
    }

    // 🔹 Retorna a lista atualizada
    public List<String> getAlunosAtualizados() {
        List<String> novaLista = new ArrayList<>();
        for (int i = 0; i < modeloLista.size(); i++) {
            novaLista.add(modeloLista.getElementAt(i));
        }
        return novaLista;
    }

    // 🔹 Quando fechar, devolve a lista para a tela que chamou
    @Override
    public void dispose() {
        if (parent instanceof CursoCadastrar cadastrar) {
            cadastrar.atualizarListaAlunos(getAlunosAtualizados());
        } else if (parent instanceof CursoEditar editar) {
            editar.atualizarListaAlunos(getAlunosAtualizados());
        }
        super.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEdicao = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnOrdenar = new javax.swing.JButton();
        panelNome = new javax.swing.JPanel();
        lblNomeAluno = new javax.swing.JLabel();
        txtNomeAluno = new javax.swing.JTextField();
        panelListaAlunos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNomeAlunos = new javax.swing.JList<>();
        btnSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(3, 34, 34));
        getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(3, 34, 34));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEdicao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEdicaoLayout = new javax.swing.GroupLayout(panelEdicao);
        panelEdicao.setLayout(panelEdicaoLayout);
        panelEdicaoLayout.setHorizontalGroup(
            panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicaoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdicionar)
                    .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrdenar, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        panelEdicaoLayout.setVerticalGroup(
            panelEdicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEdicaoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnAdicionar)
                .addGap(18, 18, 18)
                .addComponent(btnRemover)
                .addGap(18, 18, 18)
                .addComponent(btnOrdenar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(panelEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 150));

        panelNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblNomeAluno.setText("Nome:");

        javax.swing.GroupLayout panelNomeLayout = new javax.swing.GroupLayout(panelNome);
        panelNome.setLayout(panelNomeLayout);
        panelNomeLayout.setHorizontalGroup(
            panelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNomeLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblNomeAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelNomeLayout.setVerticalGroup(
            panelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeAluno)
                    .addComponent(txtNomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.add(panelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 240, 110));

        panelListaAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        listNomeAlunos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listNomeAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNomeAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listNomeAlunos);

        javax.swing.GroupLayout panelListaAlunosLayout = new javax.swing.GroupLayout(panelListaAlunos);
        panelListaAlunos.setLayout(panelListaAlunosLayout);
        panelListaAlunosLayout.setHorizontalGroup(
            panelListaAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListaAlunosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelListaAlunosLayout.setVerticalGroup(
            panelListaAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListaAlunosLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel1.add(panelListaAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 210, 240));

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(153, 153, 153));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check (1).png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 210, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String nome = txtNomeAluno.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um nome.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        modeloLista.addElement(nome);
        txtNomeAluno.setText("");
        txtNomeAluno.requestFocus();
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
         int index = listNomeAlunos.getSelectedIndex();
        if (index != -1) {
            modeloLista.remove(index);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno para remover.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        List<String> lista = new ArrayList<>();
        for (int i = 0; i < modeloLista.size(); i++) {
            lista.add(modeloLista.getElementAt(i));
        }
        Collections.sort(lista, String.CASE_INSENSITIVE_ORDER);
        modeloLista.clear();
        for (String nome : lista) {
            modeloLista.addElement(nome);
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    private void listNomeAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNomeAlunosMouseClicked
        if (evt.getClickCount() == 2) {
            int index = listNomeAlunos.locationToIndex(evt.getPoint());
            if (index != -1) {
                String antigo = modeloLista.getElementAt(index);
                String novo = JOptionPane.showInputDialog(this, "Editar nome do aluno:", antigo);
                if (novo != null && !novo.trim().isEmpty()) {
                    modeloLista.set(index, novo.trim());
                }
            }
        }
    }//GEN-LAST:event_listNomeAlunosMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Atualiza a lista na tela que chamou
    if (parent instanceof CursoCadastrar cadastrar) {
        cadastrar.atualizarListaAlunos(getAlunosAtualizados());
        cadastrar.setVisible(true);
    } else if (parent instanceof CursoEditar editar) {
        editar.atualizarListaAlunos(getAlunosAtualizados());
        editar.setVisible(true);
    }

    // Fecha esta janela
    this.dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JList<String> listNomeAlunos;
    private javax.swing.JPanel panelEdicao;
    private javax.swing.JPanel panelListaAlunos;
    private javax.swing.JPanel panelNome;
    private javax.swing.JTextField txtNomeAluno;
    // End of variables declaration//GEN-END:variables
}
