/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;
import br.com.ifba.curso.entity.Curso;
import br.com.ifba.curso.controller.CursoController;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import br.com.ifba.config.AppConfig;


/**
 * Tela principal de listagem dos cursos.
 * Exibe os cursos em uma JTable com opções para editar ou remover.
 * Também permite adicionar novos cursos.
 * @author luiza
 */
public class CursoListar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoListar.class.getName());
    private TableRowSorter<DefaultTableModel> sorter;
    private java.util.List<Curso> cursos;
    private final CursoController controller =
        context.getBean(CursoController.class);
    private static final ApplicationContext context =
        new AnnotationConfigApplicationContext(AppConfig.class);



    public CursoListar() {
        initComponents();
        configurarTabela();
        configurarPesquisaDinamica();
        configurarPlaceholderPesquisa();
        carregarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPai = new javax.swing.JPanel();
        btnAdicionarCurso = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lblLupa = new javax.swing.JLabel();
        painelTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabelaCursos = new javax.swing.JTable();
        btnHome1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        painelPai.setBackground(new java.awt.Color(0, 51, 51));
        painelPai.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdicionarCurso.setBackground(new java.awt.Color(3, 34, 34));
        btnAdicionarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdicionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCursoActionPerformed(evt);
            }
        });
        painelPai.add(btnAdicionarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 60, 40));

        txtPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPesquisar.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisar.setText("Pesquisar...");
        painelPai.add(txtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 180, 40));
        painelPai.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jPanel2.setLayout(new java.awt.BorderLayout());

        lblLupa.setBackground(new java.awt.Color(255, 255, 255));
        lblLupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lupa.png"))); // NOI18N
        jPanel2.add(lblLupa, java.awt.BorderLayout.CENTER);

        painelPai.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 210, 40));

        painelTabela.setLayout(new java.awt.BorderLayout());

        tblTabelaCursos.setBackground(new java.awt.Color(243, 236, 236));
        tblTabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Professor", "Alunos", "Remover", "Editar"
            }
        ));
        jScrollPane1.setViewportView(tblTabelaCursos);

        painelTabela.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        painelPai.add(painelTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 540, 260));

        btnHome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHome1.setForeground(new java.awt.Color(153, 153, 153));
        btnHome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        btnHome1.setText("Homescreen");
        btnHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHome1ActionPerformed(evt);
            }
        });
        painelPai.add(btnHome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 170, 40));

        getContentPane().add(painelPai);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCursoActionPerformed
        CursoCadastrar telaCadastro = context.getBean(CursoCadastrar.class);
        telaCadastro.setTitle("Cadastrar Novo Curso");
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnAdicionarCursoActionPerformed

    private void btnHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHome1ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,
        "Deseja realmente sair do programa?",
        "Sair", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnHome1ActionPerformed
    // Pesquisa dinâmica
    private void configurarPesquisaDinamica() {
        DefaultTableModel model = (DefaultTableModel) tblTabelaCursos.getModel();
        sorter = new TableRowSorter<>(model);
        tblTabelaCursos.setRowSorter(sorter);

        txtPesquisar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            private void filtrar() {
                String texto = txtPesquisar.getText().trim();
                if (texto.isEmpty() || texto.equalsIgnoreCase("Pesquisar...")) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                }
            }

            @Override public void insertUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
            @Override public void removeUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
            @Override public void changedUpdate(javax.swing.event.DocumentEvent e) { filtrar(); }
        });
    }   

    // Carrega cursos do banco e popula a tabela
    private void carregarCursos() {
    try {
        this.cursos = controller.listarCursos();

        DefaultTableModel model = (DefaultTableModel) tblTabelaCursos.getModel();
        model.setRowCount(0);

        // Adiciona os cursos à tabela
        for (Curso curso : cursos) {
            int qtdAlunos = (curso.getAlunos() != null) ? curso.getAlunos().size() : 0;
            model.addRow(new Object[]{
                curso.getNome(),
                curso.getDescricao(),
                curso.getProfessor(),
                qtdAlunos + (qtdAlunos == 1 ? " aluno" : " alunos"),
                "Editar",
                "Remover"
            });
        }

        // === RENDERIZADORES PERSONALIZADOS ===
        // Coluna "Editar"
        tblTabelaCursos.getColumnModel().getColumn(4)
                .setCellRenderer(new RenderizadorBotao("Editar"));

        // Coluna "Remover"
        tblTabelaCursos.getColumnModel().getColumn(5)
                .setCellRenderer(new RenderizadorBotao("Remover"));

        // === TOOLTIP PERSONALIZADO PARA TODAS AS COLUNAS ===
        tblTabelaCursos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(
                    JTable table, Object value, boolean isSelected,
                    boolean hasFocus, int row, int column) {

                JLabel label = (JLabel) super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);

                label.setHorizontalAlignment(SwingConstants.CENTER);
                label.setOpaque(true);
                label.setBackground(isSelected ? new Color(230, 230, 255) : Color.WHITE);

                // 🔹 Tooltip padrão: mostra o texto completo do campo
                if (value != null) {
                    label.setToolTipText(value.toString());
                } else {
                    label.setToolTipText(null);
                }

                // 🔹 Tooltip especial para a coluna "Alunos"
                if (column == 3 && row < cursos.size()) {
                    Curso curso = cursos.get(row);
                    if (curso.getAlunos() != null && !curso.getAlunos().isEmpty()) {
                        String tooltip = "<html>" + String.join("<br>", curso.getAlunos()) + "</html>";
                        label.setToolTipText(tooltip);
                    } else {
                        label.setToolTipText("Nenhum aluno cadastrado");
                    }
                }

                return label;
            }
        });

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
                "Erro ao carregar cursos: " + ex.getMessage(),
                "Erro", JOptionPane.ERROR_MESSAGE);
    }
}

    // Placeholder visual do campo de pesquisa
    private void configurarPlaceholderPesquisa() {
        txtPesquisar.setText("Pesquisar...");
        txtPesquisar.setForeground(new java.awt.Color(153, 153, 153));

        txtPesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (txtPesquisar.getText().equals("Pesquisar...")) {
                    txtPesquisar.setText("");
                    txtPesquisar.setForeground(new java.awt.Color(0, 0, 0));
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (txtPesquisar.getText().trim().isEmpty()) {
                    txtPesquisar.setText("Pesquisar...");
                    txtPesquisar.setForeground(new java.awt.Color(153, 153, 153));
                }
            }
        });
    }

    private void configurarTabela() {
    DefaultTableModel model = new DefaultTableModel(
        new Object[]{"Nome", "Descrição", "Professor", "Alunos", "Editar", "Remover"}, 0
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            // Somente colunas Editar e Remover são clicáveis
            return column == 4 || column == 5;
        }
    };

    tblTabelaCursos.setModel(model);

    // Aparência geral
    tblTabelaCursos.setRowHeight(32);
    tblTabelaCursos.setShowGrid(true);
    tblTabelaCursos.setGridColor(new java.awt.Color(220, 220, 220));
    tblTabelaCursos.setIntercellSpacing(new java.awt.Dimension(6, 4));
    tblTabelaCursos.setSelectionBackground(new java.awt.Color(230, 240, 255));
    tblTabelaCursos.setSelectionForeground(java.awt.Color.BLACK);

    // Cabeçalho
    javax.swing.table.JTableHeader header = tblTabelaCursos.getTableHeader();
    header.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    header.setBackground(new java.awt.Color(50, 100, 200));
    header.setForeground(java.awt.Color.WHITE);
    header.setOpaque(false);
    header.setReorderingAllowed(false);

    // Renderizadores
    tblTabelaCursos.getColumn("Editar").setCellRenderer(new RenderizadorBotao("Editar"));
    tblTabelaCursos.getColumn("Remover").setCellRenderer(new RenderizadorBotao("Remover"));

    // ✅ Editores específicos para cada coluna
    tblTabelaCursos.getColumn("Editar")
            .setCellEditor(new EditorBotao(new javax.swing.JCheckBox(), tblTabelaCursos, "editar"));
    tblTabelaCursos.getColumn("Remover")
            .setCellEditor(new EditorBotao(new javax.swing.JCheckBox(), tblTabelaCursos, "remover"));

    // Larguras das colunas
    tblTabelaCursos.getColumnModel().getColumn(0).setPreferredWidth(150); // Nome
    tblTabelaCursos.getColumnModel().getColumn(1).setPreferredWidth(200); // Descrição
    tblTabelaCursos.getColumnModel().getColumn(2).setPreferredWidth(150); // Professor
    tblTabelaCursos.getColumnModel().getColumn(3).setPreferredWidth(200); // Alunos
    tblTabelaCursos.getColumnModel().getColumn(4).setPreferredWidth(90);  // Editar
    tblTabelaCursos.getColumnModel().getColumn(5).setPreferredWidth(100); // Remover
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CursoListar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarCurso;
    private javax.swing.JButton btnHome1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblLupa;
    private javax.swing.JPanel painelPai;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JTable tblTabelaCursos;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
